//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RecipeSite.RecipeSOAPWebAPISvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RecipeSOAPWebAPISoap", Namespace="http://tempuri.org/")]
    public partial class RecipeSOAPWebAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddRecipeToFavoriteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveRecipeFromFavoriteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddIngredientToUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RecipeSOAPWebAPI() {
            this.Url = global::RecipeSite.Properties.Settings.Default.RecipeSite_RecipeSOAPWebAPISvc_RecipeSOAPWebAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddRecipeToFavoriteCompletedEventHandler AddRecipeToFavoriteCompleted;
        
        /// <remarks/>
        public event RemoveRecipeFromFavoriteCompletedEventHandler RemoveRecipeFromFavoriteCompleted;
        
        /// <remarks/>
        public event AddIngredientToUserCompletedEventHandler AddIngredientToUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddRecipeToFavorite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddRecipeToFavorite(int userID, int RecipeID) {
            this.Invoke("AddRecipeToFavorite", new object[] {
                        userID,
                        RecipeID});
        }
        
        /// <remarks/>
        public void AddRecipeToFavoriteAsync(int userID, int RecipeID) {
            this.AddRecipeToFavoriteAsync(userID, RecipeID, null);
        }
        
        /// <remarks/>
        public void AddRecipeToFavoriteAsync(int userID, int RecipeID, object userState) {
            if ((this.AddRecipeToFavoriteOperationCompleted == null)) {
                this.AddRecipeToFavoriteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddRecipeToFavoriteOperationCompleted);
            }
            this.InvokeAsync("AddRecipeToFavorite", new object[] {
                        userID,
                        RecipeID}, this.AddRecipeToFavoriteOperationCompleted, userState);
        }
        
        private void OnAddRecipeToFavoriteOperationCompleted(object arg) {
            if ((this.AddRecipeToFavoriteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddRecipeToFavoriteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveRecipeFromFavorite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RemoveRecipeFromFavorite(int userID, int RecipeID) {
            this.Invoke("RemoveRecipeFromFavorite", new object[] {
                        userID,
                        RecipeID});
        }
        
        /// <remarks/>
        public void RemoveRecipeFromFavoriteAsync(int userID, int RecipeID) {
            this.RemoveRecipeFromFavoriteAsync(userID, RecipeID, null);
        }
        
        /// <remarks/>
        public void RemoveRecipeFromFavoriteAsync(int userID, int RecipeID, object userState) {
            if ((this.RemoveRecipeFromFavoriteOperationCompleted == null)) {
                this.RemoveRecipeFromFavoriteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveRecipeFromFavoriteOperationCompleted);
            }
            this.InvokeAsync("RemoveRecipeFromFavorite", new object[] {
                        userID,
                        RecipeID}, this.RemoveRecipeFromFavoriteOperationCompleted, userState);
        }
        
        private void OnRemoveRecipeFromFavoriteOperationCompleted(object arg) {
            if ((this.RemoveRecipeFromFavoriteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveRecipeFromFavoriteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddIngredientToUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddIngredientToUser(int userID, int ingredientID) {
            this.Invoke("AddIngredientToUser", new object[] {
                        userID,
                        ingredientID});
        }
        
        /// <remarks/>
        public void AddIngredientToUserAsync(int userID, int ingredientID) {
            this.AddIngredientToUserAsync(userID, ingredientID, null);
        }
        
        /// <remarks/>
        public void AddIngredientToUserAsync(int userID, int ingredientID, object userState) {
            if ((this.AddIngredientToUserOperationCompleted == null)) {
                this.AddIngredientToUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddIngredientToUserOperationCompleted);
            }
            this.InvokeAsync("AddIngredientToUser", new object[] {
                        userID,
                        ingredientID}, this.AddIngredientToUserOperationCompleted, userState);
        }
        
        private void OnAddIngredientToUserOperationCompleted(object arg) {
            if ((this.AddIngredientToUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddIngredientToUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddRecipeToFavoriteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RemoveRecipeFromFavoriteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AddIngredientToUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591